'use client';

import Nav from "@/components/Nav"
import Provider from "@/components/Provider"
import Sidebar from "@/components/Sidebar"
import "@/styles/globals.css"
import { useState } from "react";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const RootLayout = ({children}) => {

  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const handleMenuClick = () => {
    setIsSidebarOpen((prevState) => !prevState);
  }

  return (
    <html lang='en'>
        <body>
            {/* <Provider> */}
                <main className="bg-slate-950 min-h-full flex flex-col">
                    <Nav handleMenuClick={handleMenuClick} />
                    
                    <div className="flex flex-row flex-1">
                      <aside>
                        <Sidebar
                          isExpanded={isSidebarOpen}
                        />
                      </aside>
                      {children}
                    </div>
                </main>
            {/* </Provider> */}
        </body>
    </html>
  )
}

export default RootLayout